In [18]:
import pandas as pd
import numpy as np

# Load the CSV file
df = pd.read_csv('C:/Users/nikhi/Desktop/blinkit data analysis and dashboard/BlinkIT Grocery Data.csv')

In [19]:
df.sample(5)
# I found so many Nan values in the Item Weight column, It should be filled before data analysis.
# Data cleaning is required in the Item Fat Content column, eg. - reg, low fat, LF.
# Found two unnamed columns, should be removed.

,Item Fat Content,Item Identifier,Item Type,Outlet Establishment Year,Outlet Identifier,Outlet Location Type,Outlet Size,Outlet Type,Item Visibility,Item Weight,Sales,Rating,Unnamed: 12,Unnamed: 13
6421,reg,FDT39,Meat,2012,OUT049,Tier 1,Medium,Supermarket Type1,0.009883,6.26,149.8366,4.0,NaN,NaN
1865,Low Fat,FDN21,Snack Foods,2022,OUT018,Tier 3,Medium,Supermarket Type2,0.077169,18.60,160.6236,4.3,NaN,NaN
7968,low fat,FDD51,Dairy,2014,OUT013,Tier 3,High,Supermarket Type1,0.119853,11.15,44.9744,4.0,NaN,NaN
1282,Low Fat,DRI11,Hard Drinks,2018,OUT027,Tier 3,Medium,Supermarket Type3,0.034238,NaN,113.2834,4.3,NaN,NaN
5900,Low Fat,NCU05,Health and Hygiene,2018,OUT027,Tier 3,Medium,Supermarket Type3,0.058452,NaN,79.9618,4.0,NaN,NaN

In [20]:
df.drop(['Unnamed: 12', 'Unnamed: 13'], axis=1, inplace=True)

In [21]:
df["Item Weight"] = df["Item Weight"].replace("", np.nan)

In [22]:
df["Item Fat Content"] = df["Item Fat Content"].replace({
    "LF": "Low Fat",
    "low fat": "Low Fat",
    "reg": "Regular"
})

In [23]:
# Creating a mapping of Item Identifier of Item Weight using mean in case multiple weights exist per item
item_weight_map = df.groupby("Item Identifier")["Item Weight"].mean()

In [24]:
item_weight_map

Item Identifier
DRA12    11.600
DRA24    19.350
DRA59     8.270
DRB01     7.390
DRB13     6.115
          ...
NCZ30     6.590
NCZ41    19.850
NCZ42    10.500
NCZ53     9.600
NCZ54    14.650
Name: Item Weight, Length: 1559, dtype: float64

In [25]:
# Filling missing values in Item Weight using the mapping
df["Item Weight"] = df["Item Weight"].fillna(df["Item Identifier"].map(item_weight_map))

In [26]:
df.head(10)

,Item Fat Content,Item Identifier,Item Type,Outlet Establishment Year,Outlet Identifier,Outlet Location Type,Outlet Size,Outlet Type,Item Visibility,Item Weight,Sales,Rating
0,Regular,FDX32,Fruits and Vegetables,2012,OUT049,Tier 1,Medium,Supermarket Type1,0.100014,15.10,145.4786,5.0
1,Low Fat,NCB42,Health and Hygiene,2022,OUT018,Tier 3,Medium,Supermarket Type2,0.008596,11.80,115.3492,5.0
2,Regular,FDR28,Frozen Foods,2016,OUT046,Tier 1,Small,Supermarket Type1,0.025896,13.85,165.0210,5.0
3,Regular,FDL50,Canned,2014,OUT013,Tier 3,High,Supermarket Type1,0.042278,12.15,126.5046,5.0
4,Low Fat,DRI25,Soft Drinks,2015,OUT045,Tier 2,Small,Supermarket Type1,0.033970,19.60,55.1614,5.0
5,Low Fat,FDS52,Frozen Foods,2020,OUT017,Tier 2,Small,Supermarket Type1,0.005505,8.89,102.4016,5.0
6,Low Fat,NCU05,Health and Hygiene,2011,OUT010,Tier 3,Small,Grocery Store,0.098312,11.80,81.4618,5.0
7,Low Fat,NCD30,Household,2015,OUT045,Tier 2,Small,Supermarket Type1,0.026904,19.70,96.0726,5.0
8,Low Fat,FDW20,Fruits and Vegetables,2014,OUT013,Tier 3,High,Supermarket Type1,0.024129,20.75,124.1730,5.0
9,Low Fat,FDX25,Canned,2018,OUT027,Tier 3,Medium,Supermarket Type3,0.101562,16.70,181.9292,5.0

In [27]:
df.to_csv("blinkit_data", index = False)

In [28]:
# item_weight_map = (
#     df.dropna(subset=["Item Weight"])
#       .drop_duplicates(subset=["Item Identifier"])
#       .set_index("Item Identifier")["Item Weight"]
# )